import type { MetadataRoute } from "next";

const BASE = "https://unclezhen.cn";

// /robots.txt — generated by Next so it stays in sync with the canonical
// base URL and sitemap. Overrides Cloudflare's content-signal-managed file
// for this origin (Cloudflare only intercepts when the path is not served
// by the origin, which Next does serve for /robots.txt).
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/admin", "/admin/", "/api", "/api/"],
      },
    ],
    sitemap: `${BASE}/sitemap.xml`,
    host: BASE,
  };
}
